struct CL {
  const long cl;
  long const lc;
  const long int cli;
  long const int lci;
  long int const lic;
  const int long cil;
  int const long icl;
  int long const ilc;
  const signed long csl;
  signed const long scl;
  signed long const slc;
  const long signed cls;
  long const signed lcs;
  long signed const lsc;
  const int signed long cisl;
  int const signed long icsl;
  int signed const long iscl;
  int signed long const islc;
  const signed int long csil;
  signed const int long scil;
  signed int const long sicl;
  signed int long const silc;
  const signed long int csli;
  signed const long int scli;
  signed long const int slci;
  signed long int const slic;
  const int long signed cils;
  int const long signed icls;
  int long const signed ilcs;
  int long signed const ilsc;
  const long int signed clis;
  long const int signed lcis;
  long int const signed lics;
  long int signed const lisc;
  const long signed int clsi;
  long const signed int lcsi;
  long signed const int lsci;
  long signed int const lsic;
};

struct CL cl;
